config/routes.rb
Rails.application.routes.draw do





  root to: "sounds#index"

  get '/login' => 'session#new'         #login form
  post '/login' => 'session#create'   # check credentials and attempt login
  delete '/login' => 'session#destroy'  # log out destroy session

  get '/search' => 'sounds#search'

  get '/record' => 'sounds#record'

  get	'/users/about'=> 'users#about'


  resources :sounds

  resources :users

  resources :comments


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :sounds
end

app/models/sound.rb
# == Schema Information
#
# Table name: sounds
#
#  id          :integer          not null, primary key
#  sound       :text
#  title       :text
#  description :text
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sound < ApplicationRecord
  # accepts_nested_attributes_for :tags
  has_many :comments
  has_and_belongs_to_many :tags
  belongs_to :user, optional: true
  belongs_to :tag, optional: true

end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_and_belongs_to_many :sounds
  belongs_to :user, optional: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :text
#  email      :text
#  website    :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  
  has_many :sounds
  has_secure_password
  validates :email, presence: true, uniqueness: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fetch_user


  private
  def fetch_user
  # session[:user_id] = nil
   @current_user = User.find session[:user_id] if session[:user_id].present?
   session[:user_id] = nil unless @current_user.present?
  end

  def check_if_logged_in
    redirect_to login_path unless @current_user.present?
  end

  def check_if_admin
    redirect_to root_path unless @current_user.present? && @current_user.is_admin
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end

  def create

    user = User.find_by email: params[:email]

    if user.present? and user.authenticate params[:password]

      session[:user_id] = user.id # set the cookie to the user id
      redirect_to user_path(user) # redirect to user profile
    else
      #mitmatch/bad credentials
      flash[:error] = "Incorrect email address and/or password"
      redirect_to login_path
    end


  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @sound = Sound.new
  end

  def create

    sound = Sound.new sound_params

    if params[:recording].present?   # live recorded sound
      req = Cloudinary::Uploader.upload(params[:recording], :resource_type => :video)
      sound.image = req['public_id']
    elsif params[:file].present?  # uploaded sound file
      req = Cloudinary::Uploader.upload(params[:file],:resource_type => :video )
      sound.image = req['public_id']
    end

    tag = Tag.find_or_create_by name: params[:tag]
    if tag.save
      sound.tags << tag
    end

    sound.user = @current_user   # associate sound with logged in user

    sound.save

    if sound.save
      # save was successful, now add cuisine associations
      tags = Tag.where id: params[:sound][:tag_ids]
      sound.tags << tags
      redirect_to sound_path(sound.id)
    else
      # render :new
    end

  end

  def edit
    @sound = Sound.find params["id"]
    redirect_to sound_path unless @current_user.id == @sound.user_id || @current_user.is_admin

  end

  def update
    sound = Sound.find params["id"]
    sound.update sound_params
    redirect_to sound_path( params["id"] )
  end

  def show
    @sounds = Sound.find params["id"]

  end

  def index
      @sounds = Sound.all

  end

  def search
    # get what the user searched for
  @search =  params[:q]

  # get what the user searched for and split each word into an array
  @searchsplit = params[:q].split(' ')

  # get what the user searched for and match it with tag list
  @result = Sound.joins(:tags).where(tags: {name: params[:q]})

  # get what the user searched for and match it with sound title list
  @titleresult = Sound.where(title: params[:q])

  # get what the user searched for and match it with the split array
  @titleresult =  Sound.where(title: [@searchsplit])

query =  params[:q]
query_length = query.split.length
@multisearch = Sound.where([(['title LIKE ?'] * query_length).join(' OR ')] + (query.split.map {|query| "%#{query}%"}))

  @sounds = Sound.all
  @tags = Tag.all

  end

  def record

  @sound = Sound.new

  end

  def destroy
    @sound = Sound.find params["id"]

    # only if admin or owner of sound can you destroy

    redirect_to sound_path unless @current_user.is_admin || @current_user.id == @sound.user_id

    Sound.find(params[:id]).destroy
    flash[:success] = "Sound deleted"
    redirect_to sounds_path

  end

  private
  def sound_params
    params.require(:sound).permit(:sound, :title, :description, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :get_user,       only: [ :show, :edit, :update ]

  before_action :check_if_admin, only: [ :index]



  def get_user
    @user = User.find params["id"]
  end


  def new
    @user = User.new

  end

  def create
    @user = User.create user_params
    if @user.id.present?
      session[:user_id] = @user.id # log in using when making a new account
      redirect_to user_path(@user.id)   # /users/17
    else
      render :new
    end

  end

  def index
    @users = User.all
  end

  def show

  end

  def edit
    # @user = User.find params["id"]
    redirect_to root_path unless @current_user == @user || @current_user.is_admin

  end

  def update

    

    @user = @current_user # makes sure user can only edit

    @user.update user_params
    redirect_to user_path( params["id"] )


  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :image, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Soundslap</title>
    <%= csrf_meta_tags %>

    <%= cloudinary_js_config %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>


    <header><h1 class="logo">Sound Slap</h1>

      <!-- hand slap - return to home page thing  -->
      <a href="/sounds"><img class='hand' src="/assets/slap.ico" alt="" ></a>


    
      <!-- search form with magnify icon -->
      <div class="search_form">
      <%= form_tag("/search", method: "get") do %>
        <%= label_tag(:q, "") %>
        <%= text_field_tag(:q,:"", placeholder: "Search", :class => 'searchfield') %>
        <%= image_submit_tag("/assets/mag.png", :class => 'mag')%>

      <% end %>
      </div>

      <!-- login and sign up -->

      <% unless @current_user.present? %>
      <div class="login">
      <%= link_to 'Login', login_path %> |
      <%= link_to 'Signup', new_user_path %>
      </div>
      <% else %>
      <p class='login'>Hello, <%= link_to @current_user.name, user_path(@current_user) %>
      - <%= link_to 'Logout', login_path, method: :delete %>
      </p>
      <% end %>

        <!-- menu -->
        <div class="dropdown">
        <button class="dropbtn">Menu</button>
        <div class="dropdown-content">
        <%= link_to 'Sounds', sounds_path %></a>
        <%= link_to 'Upload', new_sound_path %></a>
        <%= link_to 'Record', record_path %></a>
        </div>
      </div>

    </header>

        <div id='main'>

          <article><%= yield %></article>


          <nav>


          </nav>


          <aside>

          </aside>


        </div>


        <footer><br> <%= link_to 'About', users_about_path %></a> | Terms of Use</footer>

  </body>
</html>

app/views/session/new.html.erb
<h2>Login</h2>

<% if flash[:error].present? %>
<p><strong><%= flash[:error] %></strong></p>
<% end %>
<div id="emaillogin">
<%= form_tag login_path do %>
<%= label_tag 'Email' %>
<%= email_field_tag :email, nil %>
</div>
<br>

<div id="passwordlogin">
<%= label_tag 'Password' %>
<%= password_field_tag :password, nil %>
</div>
<br>
<%= submit_tag 'Login' %>
<% end %>

app/views/sounds/_form.html.erb
<%= form_for @sound, html: {multipart: true} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br><br>

  <%= f.label :info %>
  <%= f.text_field :description %>
  <br><br>

  <%= label_tag :tag %>
  <%= text_field_tag :tag %>
  <br><br>

  <div class="uploadbutton">
  <%= f.cl_upload :recording %>
  </div>
  <br>

  <%= f.submit 'Create Sound', :class => 'submitbutton' %>

<% end %>

<div class="sound"></div>

app/views/sounds/destroy.html.erb
<h1>Sounds#destroy</h1>
<p>Find me in app/views/sounds/destroy.html.erb</p>

<div class="sound"></div>

app/views/sounds/edit.html.erb
<h1>Edit Sound</h1>

<%= render partial: 'form' %>

<div class="sound"></div>

app/views/sounds/index.html.erb
<div class="soundlist">
<h3>List of sounds.</h3>

<% @sounds.each_with_index do |s, index| %>
<h3><%= link_to s.title, sound_path(s) %>
<!-- <button class="speaker" onclick="<%= s.sound%>.play()">speaker</button></h3> -->

<audio id="<%= s.id%>">
<!-- <source src="<%= s.image%>"> -->
<source src="http://res.cloudinary.com/dsxf8cujo/video/upload/v1497938309/<%=s.image%>.wav">

</audio>
<img src="assets/speaker.png" class="speaker" onclick="document.getElementById(<%= s.id%>).play()"></h3>










<script>

var play = "<%= s.sound %>";
wavesurfer.load(play);
wavesurfer.load("<%= s.sound %>");

$(".btn").click(function() {
 wavesurfer.playPause()
});

</script>




<% end %>
</div>


<!-- just to stop error in console from global wavesurfer.js plugin -->
<div class="sound"></div>

app/views/sounds/new.html.erb
<h3>Upload a new sound</h3>

<%= render partial: 'form' %>

<div class="sound"></div>

app/views/sounds/record.erb
<!-- Using the Media stream recorder plugin -->

<!-- Get all the buttons to run the code -->
<!-- experimenting with bootstrap  -->

<br>
<button class="btn btn-primary" id="start-recording" onclick="startRecording()">Record</button>
<button class="btn btn-default" id="stop-recording" onclick="stopRecording()">Stop</button>
<button class="btn btn-default play" id="play-recording" >Play</button>
<button class="btn btn-default save" id="save-recording" >Save</button>

<!-- this is the div where wavesurfer will load to -->
<div class="sound" id="record-audio"></div>

<!-- load mediastream plugin -->
<script src="//cdn.webrtc-experiment.com/commits.js"></script>
<script src="//cdn.WebRTC-Experiment.com/MediaStreamRecorder.js"></script>
<script src="//cdn.WebRTC-Experiment.com/gumadapter.js"></script>

<script>

  // set global var for luke
  var convertedsound;

  function captureUserMedia(mediaConstraints, successCallback, errorCallback) {
    navigator.mediaDevices.getUserMedia(mediaConstraints).then(successCallback).catch(errorCallback);
  }
  var mediaConstraints = {
    audio: true
  };
  function startRecording(idx) {
    $('#start-recording').disabled = true;
    audiosContainer = document.getElementById('audios-container');
    captureUserMedia(mediaConstraints, onMediaSuccess, onMediaError);
  };
  function stopRecording() {
    $('#stop-recording').disabled = true;
    mediaRecorder.stop();
    mediaRecorder.stream.stop();
    $('.start-recording').disabled = false;

  };
  var mediaRecorder;
  function onMediaSuccess(stream) {
    mediaRecorder = new MediaStreamRecorder(stream);
    mediaRecorder.stream = stream;
    mediaRecorder.mimeType = 'audio/wav';
    mediaRecorder.audioChannels = 1;
    mediaRecorder.ondataavailable = function(blob) {

      // get url of the blog so you can download to computer
      var recsound = URL.createObjectURL(blob)

      // load the blob into the wavesurfer parameters

      $("#sound_rec").val(recsound);
       wavesurfer.load(recsound);


      //  code to convert blob to wav
       var reader = new window.FileReader();
       reader.readAsDataURL(blob);
       reader.onloadend = function() {
         convertedsound =  reader.result;
         $('#recording').val( convertedsound );
         debugger;
       }




    };
    var timeInterval = 360 * 1000;
    mediaRecorder.start(timeInterval);
    $('#stop-recording').disabled = false;
  }
  function onMediaError(e) {
    console.error('media error', e);
  }
  function bytesToSize(bytes) {
    var k = 1000;
    var sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    if (bytes === 0) return '0 Bytes';
    var i = parseInt(Math.floor(Math.log(bytes) / Math.log(k)), 10);
    return (bytes / Math.pow(k, i)).toPrecision(3) + ' ' + sizes[i];
  }
  function getTimeLength(milliseconds) {
    var data = new Date(milliseconds);
    return data.getUTCHours() + " hours, " + data.getUTCMinutes() + " minutes and " + data.getUTCSeconds() + " second(s)";
  }
  window.onbeforeunload = function() {
    $('#start-recording').disabled = false;
  };

  // use jquery to control dom

  $(".sound").click(function() {
   wavesurfer.playPause()

  });
  $(".play").click(function() {
   wavesurfer.playPause()

  });

  $(".save").click(function() {
   mediaRecorder.save();
  });

  // also something not on heroku
  $("#start-mic").click(function() {
   microphone.start();
  });


</script>




<%= form_for @sound, html: {multipart: true} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br><br>

  <%= f.label :info %>
  <%= f.text_field :description %>
  <br><br>

  <%= label_tag :tag %>
  <%= text_field_tag :tag %>
  <br><br>

  <%= hidden_field_tag :recording %>

  <br>

  <%= f.submit 'Create Sound', :class => 'submitbutton' %>

<% end %>

app/views/sounds/search.html.erb
 <!-- let user know how many matches found in search -->

<p>You searched for: <%= @search %></p>
<p><%= @result.length + @multisearch.length %> results.

<!-- search for tags in tags table -->

<% @result.uniq.each do |r| %>
<h3><%= link_to r.title, sound_path(r) %>
  <audio id="<%= r.id%>"> <source src="<%= r.sound%>"> </audio>

    <!-- show speaker icon next to sound to demo it  -->
  <img src="assets/speaker.png" class="speaker" onclick="document.getElementById(<%= r.id%>).play()"></h3>
<br>

<% end %>

<!-- search through sub strings in titles in sounds table -->

<% @multisearch.uniq.each do |r| %>
<h3><%= link_to r.title, sound_path(r) %>
  <audio id="<%= r.id%>"> <source src="<%= r.sound%>"> </audio>
    
  <!-- show speaker icon next to sound to demo it  -->
  <img src="assets/speaker.png" class="speaker" onclick="document.getElementById(<%= r.id%>).play()"></h3>

<br>
<% end %>



<div class="sound"></div>

app/views/sounds/show.html.erb
<h1><%= @sounds.title %></h1>

<div class="sound"></div>

<div style="text-align: center">
  <button class="btn">
    Play
  </button>


  <button class="buttonDownload"><a href="https://res.cloudinary.com/dsxf8cujo/video/upload/v1497938309/<%= @sounds.image %>.wav" download>Download</a></button>

  </p>
</div>

<p><%= @sounds.description %></p>


<p>Uploaded by: <%= link_to @sounds.user.name, user_path(@sounds.user) %>


<!-- display tags -->
<p>Tags:
  <% @sounds.tags.each do |tag| %>

     <%= link_to tag.name, search_path(:q => tag.name) %>

  <% end %>





</p>

<% if @current_user == @user || @current_user.is_admin %>

<%= link_to 'Edit', edit_sound_path %> |
<%= link_to "Delete", @sound, method: :delete,
                                  data: { confirm: "You sure?" } %>
<% end %>


<script>

$(document).ready(function(){


  // old code before cloudinary
  var play = "<%= @sounds.image %>";

  // new code that works with cloudinary
  var cloudsound ="https://res.cloudinary.com/dsxf8cujo/video/upload/v1497938309/<%= @sounds.image %>.wav"

  // var cloudsound ="http://res.cloudinary.com/dsxf8cujo/video/upload/v1497938309/<%= @sounds.image %>.wav"

  wavesurfer.load(cloudsound);

  $(".sound").click(function() {
   wavesurfer.playPause()

  });
  $(".btn").click(function() {
   wavesurfer.playPause()


  });


});

</script>

app/views/sounds/update.html.erb
<h1>Sounds#update</h1>
<p>Find me in app/views/sounds/update.html.erb</p>

<div class="sound"></div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>

  <%= f.label :website %>
  <%= f.text_field :website %>
  <br>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>

  <%= f.submit %>

  <% end %>

  <div class="sound"></div>

app/views/users/about.html.erb
<p>Sound Slap - Slap your ear drums with epicness.</p>
<p>A community driven sample sharing website.</p>
<br>
<p>This is my first Ruby on Rails application.</p>
<p>-Jules</p>
<p>Contact: juliantreweeke@gmail.com</p>

<div class="sound"></div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

<div class="sound"></div>

app/views/users/edit.html.erb
<h2>Edit Account</h2>

<%= render partial: 'form' %>

<div class="sound"></div>

app/views/users/index.html.erb
<h1>User test</h1>

<p>List users</p>

<% @users.each do |user| %>
<p><%= link_to user.name, users_show_path(user) %></p>
<% end %>

<div class="sound"></div>


<!-- <audio id="<%= sound.title %>" controls> -->

app/views/users/new.html.erb
<h2>Create Account</h2>

<% if @user.errors.any? %>

<ol>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>

</ol>

<% end %>

<%= render partial: 'form' %>

<div class="sound"></div>

app/views/users/show.html.erb
<!-- show user profile page -->

<h2>User Details</h2>

<% if @current_user == @user %>
 <%= link_to 'Edit profile', edit_user_path(@user) %>
<% end %>


<p>Email: <%= @user.email %> </p>

<p>Name: <%= @user.name %> </p>

<img src="<%= @user.image %>" alt="">

<h3>Uploaded Sounds:</h3>
<% @user.sounds.each do |s| %>
<h4><%= link_to s.title, sound_path(s) %></h4>
<% end %>

<div class="sound"></div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

<div class="sound"></div>